### ISSUE TITLE
上海大学飞跃手册邀您共建！

### ISSUE THREAD

**Issue by chpix** [zhonger/zhonger.github.io#1]
学长您好，我是上海大学20级学弟，最近我们在筹划上海大学飞跃手册，看到学长关注了我们的Repo，请问学长愿意分享自己相关PhD的经验给到未来上大的学弟学妹们吗？
项目地址为：https://shuosc.github.io/fly/
可以加入飞跃手册交流q群：536368087

**Comment by zhonger** [comment]
需要分享申请PhD的经验？

**Comment by chpix** [comment]
> 需要分享申请PhD的经验？

嗯嗯，或者学长分享保研本校的也可以。
不过去日本的蛮少的，学长可以考虑来一波指北 : )

**Comment by zhonger** [comment]
> 嗯嗯，或者学长分享保研本校的也可以。

哈哈哈，并不是保研的，之前是考的本校。

> 不过去日本的蛮少的，学长可以考虑来一波指北 : )

感觉大家去欧美的比较多，来日本比较少。我有空的时候写一下，估计我能直接 push 上去。

**Comment by chpix** [comment]
> 感觉大家去欧美的比较多，来日本比较少。我有空的时候写一下，估计我能直接 push 上去。

如此甚好了！谢谢学长 :D

**Comment by chpix** [comment]
学长可以加个微信吗，最近我们组建了飞跃手册wx群 :D

**Comment by zhonger** [comment]
单独发个邮件给我吧，邮件回给你。或者让周典把我微信推给你，他有。
